Automatic updating of stocks data on homepage  PR-35
tommerw/StockProject pull request #34
Opened 2020-10-31 22:27 UTC by Malak-abuthaa

in this PR , the following has been done :

1. using ajax to update the Table content every 10 seconds  
2. the updating process is happening on the client side + the parsing process

2020-11-02 17:55 UTC, kamaql97 requested changes
Generally speaking, well done! 

As we discussed in the meeting, after the data update, the table rows must remain clickable (and must be linked to the relevant `single_stock` url). 

You could also use a similar method to update the table in `watchlist.html` and the data in `single_stock.html`

2020-11-03 11:24 UTC, murradkh requested changes

2020-11-03 11:24 UTC, murradkh commented on myapp/templates/index.html
> +    }, 10000)
if you can to make the interval value to be connected to the thread-scheduler interval value, so any changes there would be changed here.
you can do something similar to this `{{scheduler_interveral}}` in place of 1000, and then add provide this argument in the view when rendered the HTML.
let me know if you have any questions.

2020-11-03 11:24 UTC, murradkh commented on myapp/templates/index.html
> +            var parser = new DOMParser();
as kamal commented, this way would cause a problem on the table not clickable, because a new table inserted, click event handlers on rows

2020-11-10 19:17 UTC, kamaql97 approved these changes
Great work! Maybe consider putting all the JavaScript code in a separate file similar to what @murradkh  did in PR #33. It would also be great if we could in a future PR auto-update the table in **watchlist.html** (it uses pretty much the same code as the table in **index.html**)

2020-11-10 19:17 UTC, kamalq97 commented on myapp/scheduler/scheduler.py
> +from myrails.settings import THREAD_INTERVAL
Great idea to put all the setttings in one place and import them wherever needed!

2020-11-11 12:20 UTC, Malak-abuthaa commented on myapp/scheduler/scheduler.py
> +from myrails.settings import THREAD_INTERVAL
sure , i will do some changes on the js code

2020-11-11 21:54 UTC, closed without merging